spring.datasource.url=jdbc:postgresql://localhost:5432/matchme
spring.datasource.username=matchme
spring.datasource.password=matchme
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Directory for storing user-uploaded files
file.upload-dir=./uploads/images
# Spring will replace ${JWT_SECRET} with the value from the environment variable
jwt.secret=${JWT_SECRET:default-dev-secret-hfruweuwoajkfuowr}



